upstream_package_name: mfem
upstream_project_url: https://github.com/mfem/mfem

downstream_package_name: mfem

specfile_path: mfem.spec

jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-all
